import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

DISCLAIMER = (
    "This analysis is generated by AI for informational purposes only. "
    "It is not financial advice. Always do your own research and consult "
    "a licensed financial advisor before making investment decisions."
)
